In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Bookings-70000-Rows.csv")

In [3]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,26-07-2024,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,#NAME?
1,25-07-2024,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,#NAME?
2,30-07-2024,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,#NAME?
3,22-07-2024,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,#NAME?
4,02-07-2024,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,#NAME?

In [4]:
df.isnull().sum()

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         26930
C_TAT                         26930
Canceled_Rides_by_Customer    63987
Canceled_Rides_by_Driver      58473
Incomplete_Rides              26930
Incomplete_Rides_Reason       68516
Booking_Value                     0
Payment_Method                26930
Ride_Distance                     0
Driver_Ratings                26930
Customer_Rating               26930
Vehicle Images                    0
dtype: int64

In [5]:
if df['V_TAT'].isnull().any() :
  df['V_TAT'] = df['V_TAT'].fillna(0);

In [6]:
if df['C_TAT'].isnull().any() :
  df['C_TAT'] = df['C_TAT'].fillna(0);

In [7]:
if df['Incomplete_Rides'].isnull().any():
  df['Incomplete_Rides'] = df['Incomplete_Rides'].fillna('Yes')

In [8]:
df['Final_Payment'] = df['Booking_Value']

In [9]:
df.loc[df['Incomplete_Rides'] == 'Yes', 'Final_Payment'] = 0

In [10]:
if df['Payment_Method'].isnull().any():
  df['Payment_Method'] = df['Payment_Method'].fillna('Not applicable')

In [11]:
if df['Incomplete_Rides_Reason'].isnull().any():
  df['Incomplete_Rides_Reason'] = df['Incomplete_Rides_Reason'].fillna('No')

In [12]:
df.isnull().sum()

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                             0
C_TAT                             0
Canceled_Rides_by_Customer    63987
Canceled_Rides_by_Driver      58473
Incomplete_Rides                  0
Incomplete_Rides_Reason           0
Booking_Value                     0
Payment_Method                    0
Ride_Distance                     0
Driver_Ratings                26930
Customer_Rating               26930
Vehicle Images                    0
Final_Payment                     0
dtype: int64

In [13]:
if df['Canceled_Rides_by_Customer'].isnull().any():
  df['Canceled_Rides_by_Customer'] = df['Canceled_Rides_by_Customer'].fillna('No')

In [14]:
if df['Canceled_Rides_by_Driver'].isnull().any():
  df['Canceled_Rides_by_Driver'] = df['Canceled_Rides_by_Driver'].fillna('No')

In [15]:
if df['Driver_Ratings'].isnull().any():
  df['Driver_Ratings'] = df['Driver_Ratings'].fillna('NA')

In [16]:
if df['Customer_Rating'].isnull().any():
  df['Customer_Rating'] = df['Customer_Rating'].fillna('NA')

In [17]:
df.isnull().sum()

Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
V_TAT                         0
C_TAT                         0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Incomplete_Rides_Reason       0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
Vehicle Images                0
Final_Payment                 0
dtype: int64

In [18]:
df.shape

(71201, 21)

In [19]:
# prompt: dataframe download command

from google.colab import files
df.to_csv('Ola-70000-rows2-bookings.csv', encoding = 'utf-8-sig')
files.download('Ola-70000-rows2-bookings.csv')

In [ ]:
df

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Final_Payment
0,26-07-2024,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,...,No,Yes,Not Applicable,444,Not Applicable,0,Not Applicable,Not Applicable,#NAME?,0
1,25-07-2024,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,No,Yes,Not Applicable,158,Not Applicable,13,Not Applicable,Not Applicable,#NAME?,0
2,30-07-2024,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,No,Yes,Not Applicable,386,Not Applicable,40,Not Applicable,Not Applicable,#NAME?,0
3,22-07-2024,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,...,No,Yes,Not Applicable,384,Not Applicable,0,Not Applicable,Not Applicable,#NAME?,0
4,02-07-2024,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,No,Yes,Not Applicable,822,Not Applicable,45,Not Applicable,Not Applicable,#NAME?,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71196,19-07-2024,09:48:00,CNR3193933852,Success,CID442451,Auto,Rajajinagar,Sarjapur Road,126.0,40.0,...,No,Yes,Not Applicable,325,Not Applicable,4,Not Applicable,Not Applicable,#NAME?,0
71197,16-07-2024,05:02:00,CNR3906366271,Success,CID538007,Prime Plus,Electronic City,Varthur,49.0,30.0,...,No,Yes,Not Applicable,154,Not Applicable,28,Not Applicable,Not Applicable,#NAME?,0
71198,03-07-2024,22:14:00,CNR4789445170,Canceled by Customer,CID382728,Prime Plus,Sahakar Nagar,Rajarajeshwari Nagar,0.0,0.0,...,No,Yes,Not Applicable,447,Not Applicable,0,Not Applicable,Not Applicable,#NAME?,0
71199,29-07-2024,12:17:00,CNR5806198441,Canceled by Driver,CID686055,Bike,Rajarajeshwari Nagar,Electronic City,0.0,0.0,...,No,Yes,Not Applicable,833,Not Applicable,0,Not Applicable,Not Applicable,#NAME?,0
71200,19-07-2024,21:38:00,CNR4531167950,Success,CID923283,Prime SUV,BTM Layout,Sahakar Nagar,217.0,25.0,...,No,Yes,Not Applicable,453,Not Applicable,14,Not Applicable,Not Applicable,#NAME?,0